### PR TITLE
(XS) Account login key check improvement

### LINKED ISSUE #45: (XS)  Login.checkKeys not supporting faulty faucet created accounts
# Overview

Some older accounts were registered on a faucet that had a bug associated with key allocation. The accounts that were created through this faucet in the time frame that the bug existed has their owner and active keys swapped. This causes login attempts to fail on any dapp that does not have support for this issue. 
The peerplays-core-gui (Peerplays wallet) has some [code](https://github.com/peerplays-network/peerplays-core-gui/blob/b4cbda1e404baad18370944205db64d2bfc63e2e/src/services/WalletService.js#L118) within its login functions to handle this issue. Unfortunately, this fix has not been implemented into the peerplaysjs-lib.

## Details

Within the Login.[checkKeys](https://github.com/peerplays-network/peerplaysjs-lib/blob/404e7dc626685847210026acab374ee204975657/lib/chain/src/AccountLogin.js#L54) function, ~~additional code may be required. If a checkKeys attempt fails, the owner key is to be checked against the active key instead (swap)~~ keys provided to the function are checked recursively against the active key on chain. Under ideal usage, a user will provide the Login class the correct array of roles (`['owner', 'active', 'memo']`) and the checkKeys function will iterate over all keys provided. This way, each key passed in will be checked against the active public key that exists on the Peerplays blockchain.

There is also a dependency of the prefix. For simple dapps, one cannot reliably use the peerplaysjs-lib without instantiating a websocket connection and using that for all blockchain interactions. There needs to be support added to the checkKeys function to pass in a custom prefix so that users are not forced to instantiate the ws chainstore and set the prefix through it.

image

## Impact

There will be a bit more time required to re-process the key check as a result of this required fix but it is a low complexity solution and the algorithms in use are also low complexity so there ends up being no human noticeable increase in login time.

- millisecond(s), or less, speed decrease
- tests related to changes required must pass (change as needed)

### Estimate

3-4 development hours (xxs)
- requires cleanup of prior release (pre-release -> release) and then syncing with this branch
- cut new version/release after this branch has merged (pre-release)

## PBSA / Developer tasks

* [x] Evaluate / Prioritize Bug Report
* [x] Refine User Stories / Requirements
* [x] Define Test Cases
* [x] Design / Develop Solution
* [ ] Perform QA/Testing
* [x] Update Documentation

### PR DESCRIPTION
**Pull request by mseaward**
### Purpose

Some older accounts were registered on a faucet that had a bug associated with key allocation. The accounts that were created through this faucet in the time frame that the bug existed has their owner and active keys swapped. This causes login attempts to fail on any dapp that does not have support for this issue. 
The peerplays-core-gui (Peerplays wallet) has some [code](https://github.com/peerplays-network/peerplays-core-gui/blob/b4cbda1e404baad18370944205db64d2bfc63e2e/src/services/WalletService.js#L118) within its login functions to handle this issue. Unfortunately, this fix has not been implemented into the peerplaysjs-lib.

The GitHub issue is: #45 

## Instructions to Verify

**Steps To Reproduce:**

1. Developer should be able to use the AccountLogin.js (Login) class in a sandbox environment and mock an account login successfully [requires an actual account and some pre-req info to be passed to the class].

**Expected Behavior**

One should be able to make use of the AccountLogin.js (Login) class without having to instantiate the chainstore and/or a websocket connection.

### Declarations

Check these if you believe they are true

* [X] The code base is in a better state after this PR
* [X] The level of testing this PR includes is appropriate
* [x] All tests pass using the self-service CI/Gitlab.
* [X] Changes to the codebase are well documented
* [X] Testing steps for the QA team / community is shared

### Reviewers

@MuffinLightning 

### FYIs

In order to test, install this branch on a stable Peerplays dapp and ensure that no new bugs arise.

### Closing issues

Closes #45

### CODE REVIEW

**Comment by mseaward** [comment]
note: don't merge until #49 is merged

**Review by MuffinLightning — DISMISSED** [review]
LGTM

**Comment by belakon1975** [comment]
@mseaward  please estimate! xxs=0.5 days, xs=1 day , s=2 days , m=3 days, L=5 days, XL=8 days etc.

**Comment by mseaward** [comment]
> @mseaward please estimate! xxs=0.5 days, xs=1 day , s=2 days , m=3 days, L=5 days, XL=8 days etc.

@belakon1975 this is a pull request for an existing issue #45 as indicated in the description of this pull request. I am not sure where "SC-8" came from as there is no issue for that on this repository. I will put the estimate on the issue this pull request is associated with (#45 )

**Review by MuffinLightning — APPROVED** [review]

**Pull request merged**
